### ISSUE TITLE
Load balancer configuration not exported fully

### ISSUE THREAD

**Issue by nabeen-najeeb** [Azure/aztfexport#533] opened 2024-06-06 10:37 UTC
- Load balancer rules and probes are not captured automatically. I am able to capture the rules and probes by manually adding it to the mapping file and then using the map command but not automatically when using `rg` command.
- Load balancer frontend IP configs is only partially captured. Only the name and zone are getting captured. All other details are missing.

**Comment by magodo** [comment] 2024-06-07 00:59
@nabeen-najeeb Thank your reaching out!

The 1st issue for missing lb rule/probe has been fixed in https://github.com/Azure/aztfexport/pull/524, which is included in the v0.14.1.

The 2nd one is by design, as those other fields are defined as Computed & Optional, which will be omit from exporting by default. If you do want to export all non computed only fields, you can add the option `--full-properties`.

**Comment by nabeen-najeeb** [comment] 2024-06-07 06:30
@magodo Thank you. I am using v0.14.1 and I can see that the fix is not available in the version - https://github.com/Azure/aztfexport/compare/v0.14.1...refs/heads/main. 

`--full-properties` resolved the 2nd issue.

**Comment by magodo** [comment] 2024-06-07 07:36
My fault, will do another release soon

**Closed** 2024-06-07 10:22 UTC
Labels: question
